# Generated by Django 5.2 on 2025-04-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlloqualita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOSSIER_BACC', 'Dossier BACC'), ('DOSSIER_PL', 'Dossier PL'), ('EREDI', 'Eredi'), ('RINTRACCI', 'Rintracci')], max_length=20)),
                ('expression', models.TextField(blank=True, default='False', help_text='Espressione Python su df,lav,pen,ban,tel,note,erd,res. Esempio: "df==\'SI\' or (lav and pen and ban)"', null=True)),
                ('score_letter', models.CharField(max_length=2)),
                ('score_value', models.IntegerField()),
            ],
            options={
                'ordering': ('category',),
                'unique_together': {('category', 'expression')},
            },
        ),
    ]
