# Generated by Django 5.2 on 2025-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlloqualita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOSSIER_BACC', 'Dossier BACC'), ('DOSSIER_PL', 'Dossier PL'), ('EREDI', 'Eredi'), ('RINTRACCI', 'Rintracci')], max_length=20)),
                ('condition', models.CharField(choices=[('decesso', 'Decesso flag = SI'), ('lavoro_banca', 'Lavoro/Pensione AND Banca'), ('lavoro_no_banca', 'Lavoro/Pensione SOLO'), ('contattato', 'Telefono + “contattato” in note'), ('default', 'Default (tutti gli altri)'), ('eredi_chiamato', 'Eredi: chiamato'), ('eredi_default', 'Eredi: altri'), ('rintracci_pos', 'Rintracci: residenza OR deceduto'), ('rintracci_neg', 'Rintracci: altri')], max_length=20)),
                ('score_letter', models.CharField(max_length=2, verbose_name='Lettera')),
                ('score_value', models.IntegerField(verbose_name='Valore numerico')),
            ],
            options={
                'ordering': ('category', 'condition'),
                'unique_together': {('category', 'condition')},
            },
        ),
    ]
