# Generated by Django 5.2 on 2025-04-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlloqualita', '0004_alter_scoringrule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringrule',
            name='condition',
        ),
    ]
