# Generated by Django 5.2 on 2025-04-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlloqualita', '0005_remove_scoringrule_condition'),
    ]

    operations = [
    ]
