# Generated by Django 5.2 on 2025-04-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlloqualita', '0006_alter_scoringrule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoringrule',
            unique_together={('category', 'expression')},
        ),
    ]
