# Generated by Django 5.2 on 2025-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlloqualita', '0002_scoringrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringrule',
            options={'ordering': ('category',)},
        ),
        migrations.AddField(
            model_name='scoringrule',
            name='expression',
            field=models.TextField(default=False, help_text='Espressione Python su df,lav,pen,ban,tel,note,erd,res. Esempio: "df==\'SI\' or (lav and pen and ban)"'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='score_letter',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='score_value',
            field=models.IntegerField(),
        ),
    ]
