# Generated by Django 5.2 on 2025-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlloqualita', '0003_alter_scoringrule_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoringrule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='expression',
            field=models.TextField(blank=True, default='False', help_text='Espressione Python su df,lav,pen,ban,tel,note,erd,res. Esempio: "df==\'SI\' or (lav and pen and ban)"', null=True),
        ),
    ]
